// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC90hFfSwuWapiJbv_12mEeV9RhfxJsTTk',
    appId: '1:712126556649:web:3c324195e18f81f9530378',
    messagingSenderId: '712126556649',
    projectId: 'camera-slider',
    authDomain: 'camera-slider.firebaseapp.com',
    storageBucket: 'camera-slider.firebasestorage.app',
    measurementId: 'G-LQ0P1DFMJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDhbDkBMTXm_PoRMze2FVRYeMBg6Ibwc',
    appId: '1:712126556649:android:b3d4bb65ddfd1c23530378',
    messagingSenderId: '712126556649',
    projectId: 'camera-slider',
    storageBucket: 'camera-slider.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwRPUnX38jwK5ODa3LGBA1NnlKHJ7yqAI',
    appId: '1:712126556649:ios:e54c78b5a36b5e73530378',
    messagingSenderId: '712126556649',
    projectId: 'camera-slider',
    storageBucket: 'camera-slider.firebasestorage.app',
    iosBundleId: 'com.example.cameraSlider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwRPUnX38jwK5ODa3LGBA1NnlKHJ7yqAI',
    appId: '1:712126556649:ios:e54c78b5a36b5e73530378',
    messagingSenderId: '712126556649',
    projectId: 'camera-slider',
    storageBucket: 'camera-slider.firebasestorage.app',
    iosBundleId: 'com.example.cameraSlider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC90hFfSwuWapiJbv_12mEeV9RhfxJsTTk',
    appId: '1:712126556649:web:5b1775f596c3c5e7530378',
    messagingSenderId: '712126556649',
    projectId: 'camera-slider',
    authDomain: 'camera-slider.firebaseapp.com',
    storageBucket: 'camera-slider.firebasestorage.app',
    measurementId: 'G-HVPJNJG4LW',
  );
}
